### PR TITLE
Feature: Add Functional component support

### PR DESCRIPTION
**Pull request by blake-newman**
I'm not an expert with types, but this seemed to work for me to get functional components working with correct typing inside component and in JSX

### CODE REVIEW

**Comment by wonderful-panda** [comment]
I'm considering changing APIs for Vue 2.5 now.

And I think `createComponent` should be deprecated because `Vue.extend` definition becomes complicated and copying it into our d.ts is not good way.

I'll add another API which is more Vue 2.5 friendly.

**Comment by blake-newman** [comment]
Nice, sounds like a good idea. You possible can utilise the typing, to remove need for prop interface. 

I got it working when playing around. It's a niave set of overrides, but utilising it in the API you have should work wonders. I'll send you over a Gist

**Comment by eshimischi** [comment]
@wonderful-panda hope that you will update [vue-typed-component](https://github.com/wonderful-panda/vue-typed-component) also and some docs/examples maybe. Thanks!

**Comment by iztsv** [comment]
@wonderful-panda did you add API for creating functional components?
Unfortunately, I cannot find any examples about it.

**Comment by eshimischi** [comment]
> @wonderful-panda did you add API for creating functional components?
> Unfortunately, I cannot find any examples about it.

nope he didn't & Functional components are still in draft and realization may be changed, so i see no way to add this feature so far or before the final realization by vue team.

**Comment by eshimischi** [comment]
> @wonderful-panda did you add API for creating functional components?
> Unfortunately, I cannot find any examples about it.

nope he didn't

**Comment by wonderful-panda** [comment]
@iztsv 

Basic example is below.

```typescript
import * as tsx from "vue-tsx-support";
const MyComponent = tsx.component({
  props: { foo: String },
  functional: true,
  render(_h, ctx) {
    return <div>{ctx.props.foo}</div>;
  }
});
```

FYI, I wrote babel plugin which transpiles arrow function to functional component.
(Similar to babel-vue-sugar-functional-vue, but more TypeScript friendly.)

https://github.com/wonderful-panda/babel-plugin-vue-tsx-functional

**Pull request closed without merging**
