### PR TITLE
[fix] scoped slot typing

### LINKED ISSUE #11: Improve ScopedSlot type
Currently, scopedSlots are defined to accept a function that returns `VNodeChildrenArrayContents | string`:

```ts
// vnode.d.ts
export type ScopedSlot = (props: any) => VNodeChildrenArrayContents | string;
```

So, acoording to the type definition a scoped slot function always has to return an array:
```tsx
// scopedSlot callback:
renderSlotContent( props: ScopeProps ) {
      // must return array according to type definition:
      return ( [ <span>asdadsf</span> ] );
},
```
But, it is also possible to directly return an element / node without wrapping it in array:
```tsx
// scopedSlot callback:
renderSlotContent( props: ScopeProps ) {
      // vue accepts this and it renders correctly
      return <span>asdadsf</span>;
},
```
At the same time typescript complains about this, because it assumes that the return type must be `VNodeChildrenArrayContents | string`.

Now, I have almost no knowledge about Vue render functions and VNodes and such...but why does the return type has to be an array? Is there a specific reason?

And, can that type definition be made more flexible so typescript stops complaining if the callback function returns a node directly (without wrapping it in an array)?

Thank you very much,
and thanks for this great library!

### PR DESCRIPTION
**Pull request by blake-newman**
- Update vue dependencies
- Fix scoped slots definitions to be compatible with Vue typings
- ScopedSlots can be undefined as there is no guarantee that the scoped
slot has to be passed. https://github.com/vuejs/vue/commit/448ba65d2b139b29f1e6891add9925ac22ffe10b
- Fixes #11

### CODE REVIEW

**Comment by chanlito** [comment]
Hey @blake-newman just out of curiosity which version of typescript are you on?

**Comment by blake-newman** [comment]
This will be the latest version 3.1.2 for our projects. 

This project uses: https://github.com/wonderful-panda/vue-tsx-support/blob/master/package.json#L56

**Comment by wonderful-panda** [comment]
I don't want to make all scoped slots optional unconditionally.

I think it would be better that optional slots are marked explicitly like below.

```typescript
export interface MyScopedSlots {
  foo?: string;  // optional
  bar: string; // required
}

export const MyComponent = tsx.componentFactoryOf<{}, MyScopedSlots>().create({
  render(): VNode {
    const { foo, bar } = this.$scopedSlots;
    return (
      <div>
        { foo ? foo("foo") : "default foo" }
        { bar("bar") }
      </div>
    );
  }
});
```

**Comment by blake-newman** [comment]
That makes sense, aslong as the usage (`<Component scopedSlots={{...}} />`) enforces that scoped slots must be passed if declared. This way you can't run into a runtime error with scoped slots.

Do you know if this is currently the case? I will amend this PR to make the typing more strict.

**Pull request closed without merging**
